

services:
  web:
    build: .
    ports:
      - "8900:80"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: portfolio
    ports:
      - "3312:3306"
    networks:
      - my_network
    volumes:
      - ./portfolio.sql:/docker-entrypoint-initdb.d/portfolio.sql
networks:
  my_network:
    driver: bridge
