version: '3.8'

services:
  web:
    build: .
    ports:
      - "8500:80"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./project.sql:/docker-entrypoint-initdb.d/project.sql

networks:
  my_network:
    driver: bridge
